export const Colors = {
  background: '#FAFAFA',
  surface: '#FFFFFF',
  surfaceElevated: '#FFFFFF',
  textPrimary: '#1A1A1A',
  textSecondary: '#6B6B6B',
  textTertiary: '#9E9E9E',
  divider: '#E8E8E8',
  border: '#F0F0F0',
  accent: '#2D2D2D',
  accentSubtle: '#F5F5F5',
  availableGreen: '#34A853',
  availableGreenBg: '#E8F5E9',
  availableAmber: '#F9A825',
  takenGrey: '#D9D9D9',
  shimmerBase: '#EEEEEE',
  shimmerHighlight: '#F5F5F5',
  error: '#D32F2F',
};
